book:
    title:            "Project Tangelo"
    author:           "Team 3"
    edition:          ""
    language:         en
    publication_date: ~

    generator: { name: easybook, version: 4.8 }

    contents:
        # available content types: acknowledgement, afterword, appendix, author,
        # chapter, conclusion, cover, dedication, edition, epilogue, foreword,
        # glossary, introduction, license, lof (list of figures), lot (list of
        # tables), part, preface, prologue, title, toc (table of contents)
        - { element: cover }
        - { element: toc   }
        - { element: chapter, number: 1, content: 1-introduction-and-background.md }
        - { element: chapter, number: 2, content: 2-system-functional-specification.md }
        - { element: chapter, number: 3, content: 3-system-performance-requirements.md }
        - { element: chapter, number: 4, content: 4-system-design-overview.md }
        - { element: chapter, number: 5, content: 5-system-data-structure-specifications.md }
        - { element: chapter, number: 6, content: 6-module-design-specification.md }
        - { element: chapter, number: 7, content: 7-system-verifications.md }
        - { element: chapter, number: 8, content: 8-conclusions.md }
        - { element: chapter, number: 9, content: 9-appendix.md }
        - { element: chapter, number: 10, content: 10-program-listings.md }
        - { element: chapter, number: 11, content: 11-api.md }

    editions:
        ebook:
            format:         epub
            highlight_code: false
            include_styles: true
            labels:         ['appendix', 'chapter']  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       1
                elements:   ["appendix", "chapter", "part"]

        print:
            format:         pdf
            highlight_code: true
            include_styles: true
            isbn:           ~
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            margin:
                top:        25mm
                bottom:     25mm
                inner:      30mm
                outter:     20mm
            page_size:      A4
            theme:          clean
            toc:
                deep:       4
                elements:   ["appendix", "chapter", "part"]
            two_sided:      true

        web:
            format:         html
            highlight_code: true
            include_styles: true
            labels:         ["appendix", "chapter"]  # labels also available for: "figure", "table"
            theme:          clean
            toc:
                deep:       2
                elements:   ["appendix", "chapter"]

        website:
            extends:        web
            format:         html_chunked
